/**
 * Hierarchical Text Chunker for RAG
 *
 * Produces 3 levels of chunks:
 *   L0 — Document summary (generated by AI, stored separately)
 *   L1 — Section-level chunks (~1500-2000 chars) — broader context
 *   L2 — Detail chunks (~600-800 chars) with overlap — precision retrieval
 *
 * The hierarchy enables multi-resolution search:
 *   1. Find relevant documents via L0 summaries
 *   2. Find relevant sections via L1 chunks
 *   3. Find exact passages via L2 chunks
 *   4. Use parent L1 as context when presenting L2 results
 */

export interface TextChunk {
    text: string;
    index: number;
    level: 1 | 2;                // L1 = section, L2 = detail
    parentIndex: number | null;  // L2 points to its parent L1 index
    tokenEstimate: number;
    sectionTitle?: string;       // detected section heading (if any)
}

// Rough estimate: 1 token ~ 4 chars for Italian/English
const CHARS_PER_TOKEN = 4;

// L1 — Section chunks (broader context)
const L1_TARGET_CHARS = 2000;
const L1_MIN_CHARS = 200;

// L2 — Detail chunks (precision)
const L2_TARGET_CHARS = 800;
const L2_OVERLAP_CHARS = 200;
const L2_MIN_CHARS = 100;

// Hard ceiling — must stay safely below OpenAI text-embedding-3-small's
// 8192-token input limit. We keep ~15% margin for tokenizer variance
// (CJK, accented chars, code, URLs) and to absorb any contextual prefixing.
const MAX_CHUNK_TOKENS = 7000;
const MAX_CHUNK_CHARS = MAX_CHUNK_TOKENS * CHARS_PER_TOKEN; // 28000

/**
 * Main entry: produce hierarchical chunks from extracted text.
 */
export function chunkText(text: string, metadata?: { fileName?: string }): TextChunk[] {
    const cleaned = cleanText(text);

    if (!cleaned || cleaned.length < L2_MIN_CHARS) {
        return [];
    }

    // If text is very short, return as single L1 chunk
    if (cleaned.length <= L1_TARGET_CHARS) {
        return enforceChunkLimits([{
            text: cleaned,
            index: 0,
            level: 1,
            parentIndex: null,
            tokenEstimate: estimateTokens(cleaned),
        }]);
    }

    // Step 1: Split into L1 section chunks
    const l1Chunks = createL1Chunks(cleaned);

    // Step 2: For each L1, create L2 detail chunks
    const allChunks: TextChunk[] = [];
    let globalIndex = 0;

    for (const l1 of l1Chunks) {
        // Add the L1 chunk
        const l1Index = globalIndex++;
        allChunks.push({
            text: l1.text,
            index: l1Index,
            level: 1,
            parentIndex: null,
            tokenEstimate: estimateTokens(l1.text),
            sectionTitle: l1.sectionTitle,
        });

        // Create L2 detail chunks from this L1
        if (l1.text.length > L2_TARGET_CHARS * 1.5) {
            const l2Chunks = createL2Chunks(l1.text);
            for (const l2 of l2Chunks) {
                allChunks.push({
                    text: l2.text,
                    index: globalIndex++,
                    level: 2,
                    parentIndex: l1Index,
                    tokenEstimate: estimateTokens(l2.text),
                });
            }
        }
    }

    return enforceChunkLimits(allChunks);
}

/**
 * Final safety pass: any chunk exceeding MAX_CHUNK_CHARS (e.g. an unbreakable
 * paragraph, table dump, or section without sentence boundaries) is split
 * hierarchically — paragraph → newline → sentence → word → char.
 *
 * Preserves L1/L2 levels and parent links: when a chunk gets split into N pieces,
 * the first keeps the original index/parent, the rest become siblings inserted
 * inline (we then re-index globally so DB inserts stay sequential).
 */
function enforceChunkLimits(chunks: TextChunk[]): TextChunk[] {
    const out: TextChunk[] = [];

    for (const chunk of chunks) {
        if (chunk.text.length <= MAX_CHUNK_CHARS) {
            out.push(chunk);
            continue;
        }

        const pieces = splitOversized(chunk.text, MAX_CHUNK_CHARS);
        for (const piece of pieces) {
            out.push({
                text: piece,
                index: 0, // re-indexed below
                level: chunk.level,
                parentIndex: chunk.parentIndex,
                tokenEstimate: estimateTokens(piece),
                sectionTitle: chunk.sectionTitle,
            });
        }
    }

    // Re-index globally and remap L2 parentIndex references onto the new L1 positions.
    // Order is preserved by `out`, so we just need: for each original L1 index,
    // what is the slot of its first piece in `out`?
    const oldToNewL1: Record<number, number> = {};
    let outCursor = 0;
    for (const original of chunks) {
        const produced = original.text.length <= MAX_CHUNK_CHARS
            ? 1
            : splitOversized(original.text, MAX_CHUNK_CHARS).length;
        if (original.level === 1) oldToNewL1[original.index] = outCursor;
        outCursor += produced;
    }

    return out.map((c, i) => ({
        ...c,
        index: i,
        parentIndex: c.level === 2 && c.parentIndex !== null
            ? (oldToNewL1[c.parentIndex] ?? null)
            : c.parentIndex,
    }));
}

/**
 * Split a too-large text into pieces under the limit, picking the coarsest
 * boundary that works at each level so we preserve as much semantic locality
 * as possible.
 */
function splitOversized(text: string, maxLen: number): string[] {
    if (text.length <= maxLen) return [text];

    // Try delimiters from coarsest to finest
    const delimiters: Array<RegExp | string> = [
        /\n{2,}/,    // paragraph breaks
        /\n/,        // line breaks
        /(?<=[.!?;])\s+/, // sentence boundaries
        /\s+/,       // word boundaries
    ];

    for (const delim of delimiters) {
        const parts = text.split(delim).filter(p => p.length > 0);
        // If splitting on this delimiter actually helps (more than one part
        // and largest part is smaller than original), use a greedy packer.
        if (parts.length > 1 && Math.max(...parts.map(p => p.length)) < text.length) {
            const packed = greedyPack(parts, maxLen);
            // If any single piece still exceeds the cap, recurse with finer delimiter
            if (packed.every(p => p.length <= maxLen)) return packed;
            // recurse: any oversized piece gets split again
            return packed.flatMap(p => p.length <= maxLen ? [p] : splitOversized(p, maxLen));
        }
    }

    // Last resort: hard char-slice. Still respects the cap.
    const pieces: string[] = [];
    for (let i = 0; i < text.length; i += maxLen) {
        pieces.push(text.slice(i, i + maxLen));
    }
    return pieces;
}

/**
 * Greedy first-fit pack: concatenate consecutive parts (separated by space)
 * until adding the next would exceed maxLen, then start a new piece.
 */
function greedyPack(parts: string[], maxLen: number): string[] {
    const out: string[] = [];
    let buf = '';
    for (const part of parts) {
        if (!buf) {
            buf = part;
            continue;
        }
        if (buf.length + 1 + part.length <= maxLen) {
            buf += ' ' + part;
        } else {
            out.push(buf);
            buf = part;
        }
    }
    if (buf) out.push(buf);
    return out;
}

/**
 * Create L1 section-level chunks.
 * Tries to split on natural section boundaries (headings, double newlines, major breaks).
 */
function createL1Chunks(text: string): Array<{ text: string; sectionTitle?: string }> {
    // Try to detect section boundaries
    const sections = splitIntoSections(text);

    if (sections.length > 1) {
        // Merge small sections into their neighbors
        return mergeSections(sections, L1_TARGET_CHARS, L1_MIN_CHARS);
    }

    // No clear sections found — split by paragraph groups
    return splitByParagraphGroups(text, L1_TARGET_CHARS);
}

/**
 * Create L2 detail chunks with overlap from a section text.
 */
function createL2Chunks(text: string): Array<{ text: string }> {
    const sentences = splitIntoSentences(text);
    const chunks: Array<{ text: string }> = [];

    let currentSentences: string[] = [];
    let currentLength = 0;

    for (const sentence of sentences) {
        if (currentLength + sentence.length > L2_TARGET_CHARS && currentSentences.length > 0) {
            chunks.push({ text: currentSentences.join(' ').trim() });

            // Overlap: keep last sentences
            const overlapSentences: string[] = [];
            let overlapLength = 0;
            for (let j = currentSentences.length - 1; j >= 0; j--) {
                if (overlapLength + currentSentences[j].length > L2_OVERLAP_CHARS) break;
                overlapSentences.unshift(currentSentences[j]);
                overlapLength += currentSentences[j].length;
            }

            currentSentences = [...overlapSentences];
            currentLength = overlapLength;
        }

        currentSentences.push(sentence);
        currentLength += sentence.length;
    }

    // Last chunk
    if (currentSentences.length > 0) {
        const chunkText = currentSentences.join(' ').trim();
        if (chunkText.length >= L2_MIN_CHARS) {
            chunks.push({ text: chunkText });
        }
    }

    return chunks;
}

/**
 * Detect section boundaries in text.
 * Looks for markdown-style headings, numbered sections, ALL CAPS headings,
 * and structural separators.
 */
function splitIntoSections(text: string): Array<{ text: string; title?: string }> {
    // Patterns that indicate a new section
    const sectionPattern = /(?:^|\n)(?:#{1,4}\s+.+|(?:Art(?:icolo)?\.?\s*\d+|ARTICOLO\s+\d+).+|\d+\.\s+[A-ZÀ-Ü].{5,}|[A-ZÀ-Ü]{3,}(?:\s+[A-ZÀ-Ü]+){1,}|---+|===+)/gm;

    const matches: Array<{ index: number; title: string }> = [];
    let match;

    while ((match = sectionPattern.exec(text)) !== null) {
        matches.push({
            index: match.index,
            title: match[0].trim().replace(/^#+\s*/, '').replace(/^---+$/, '').substring(0, 100),
        });
    }

    if (matches.length < 2) {
        return [{ text, title: undefined }];
    }

    const sections: Array<{ text: string; title?: string }> = [];

    for (let i = 0; i < matches.length; i++) {
        const start = matches[i].index;
        const end = i + 1 < matches.length ? matches[i + 1].index : text.length;
        const sectionText = text.slice(start, end).trim();

        if (sectionText) {
            sections.push({
                text: sectionText,
                title: matches[i].title || undefined,
            });
        }
    }

    // Add text before first section
    if (matches[0].index > 50) {
        sections.unshift({
            text: text.slice(0, matches[0].index).trim(),
            title: 'Introduzione',
        });
    }

    return sections;
}

/**
 * Merge small sections into neighbors to meet minimum size.
 */
function mergeSections(
    sections: Array<{ text: string; title?: string }>,
    target: number,
    minimum: number
): Array<{ text: string; sectionTitle?: string }> {
    const result: Array<{ text: string; sectionTitle?: string }> = [];
    let buffer = '';
    let bufferTitle: string | undefined;

    for (const section of sections) {
        if (buffer.length + section.text.length <= target) {
            buffer += (buffer ? '\n\n' : '') + section.text;
            if (!bufferTitle) bufferTitle = section.title;
        } else {
            if (buffer.length >= minimum) {
                result.push({ text: buffer, sectionTitle: bufferTitle });
            }
            buffer = section.text;
            bufferTitle = section.title;
        }
    }

    if (buffer.length >= minimum) {
        result.push({ text: buffer, sectionTitle: bufferTitle });
    }

    return result;
}

/**
 * Split text by paragraph groups when no clear sections exist.
 */
function splitByParagraphGroups(
    text: string,
    targetSize: number
): Array<{ text: string; sectionTitle?: string }> {
    const paragraphs = text.split(/\n\n+/).filter(p => p.trim().length > 0);
    const groups: Array<{ text: string }> = [];

    let current: string[] = [];
    let currentLength = 0;

    for (const para of paragraphs) {
        if (currentLength + para.length > targetSize && current.length > 0) {
            groups.push({ text: current.join('\n\n') });
            current = [];
            currentLength = 0;
        }
        current.push(para);
        currentLength += para.length;
    }

    if (current.length > 0) {
        groups.push({ text: current.join('\n\n') });
    }

    return groups;
}

/**
 * Split text into sentences for L2 chunking.
 */
function splitIntoSentences(text: string): string[] {
    const paragraphs = text.split(/\n\n+/);
    const sentences: string[] = [];

    for (const paragraph of paragraphs) {
        if (!paragraph.trim()) continue;

        // Split on sentence-ending punctuation followed by space + uppercase
        const parts = paragraph.split(/(?<=[.!?;])\s+(?=[A-ZÀ-Ü\d])/);

        for (const part of parts) {
            const trimmed = part.trim();
            if (trimmed) sentences.push(trimmed);
        }
    }

    // Fallback: if very few sentences, split on newlines
    if (sentences.length <= 2 && text.length > L2_TARGET_CHARS) {
        return text.split(/\n+/).filter(s => s.trim().length > 0);
    }

    return sentences;
}

// --- Utilities ---

function cleanText(text: string): string {
    return text
        .replace(/\r\n/g, '\n')
        .replace(/\n{4,}/g, '\n\n\n')
        .replace(/[ \t]{3,}/g, ' ')
        .trim();
}

export function estimateTokens(text: string): number {
    return Math.ceil(text.length / CHARS_PER_TOKEN);
}
